### ISSUE TITLE
Images in the pluto notebook are not recognizable in darkmode

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/TrainRuns.jl-Tutorials#1]
![image](https://github.com/railtoolkit/TrainRuns.jl-Tutorials/assets/10660618/7913a035-f704-4457-8e78-f7af27b2758c)
In darkmode the contrast of all svg images is very low and hardly recognizable.

**Comment by kaat0** [comment]
True! Do you know a way to switch images when darkmode is enabled?

**Comment by apriljunge** [comment]
Unfortunately not. I have now read through the pluto source code. It looks like the darkmode is not recognizable in julia. The darkmode is only styled directly [via css](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). You would probably have to find a way to read CSS variables or JavaScript into a Julia variable. Or you could add some custom css.

**Comment by apriljunge** [comment]
The fastest way would be to add a background color to the pngs
